### PR TITLE
Get language source from storj

### PR DESCRIPTION
**Pull request by kaichaosun**
Related to https://github.com/juntofoundation/flux/issues/187

### CODE REVIEW

**Comment by jdeepee** [comment]
Probably an issue to leak the secret key here right? I think the secret key must be provided using the language settings functionality; let me double check with Nico about how we can best do this

**Comment by jdeepee** [comment]
Be careful with your storj account now; its possible that secret key is going to be picked up by a bot and used

**Comment by kaichaosun** [comment]
Yeah, this is an issue, but acceptable for test purpose, there need to be a better permission management on who can publish languages.
Now every agent can do this by create a new community, we need to something like KYC'd users or paid users can do this.
The credential can be revoked once I found something bad happpens.

**Comment by jdeepee** [comment]
Yeah I think you are right @kaichaosun, for now we can merge and use, I guess we should not have any problems.

Yes that is what the ad4m kyc / token economics model is designed to do! Definitely an important piece for protection of our public infrastructure.

**Pull request merged**
